### ISSUE TITLE
Emissions Chart:  Lines Colored with a Black Background

### ISSUE THREAD

**Issue by UPstartDeveloper** [UPstartDeveloper/climate-change-analysis#2]

**Comment by rahulbhatt1899** [comment]
Could you provide a detailed description of what you want?

From what I have understood, you want this line colored, with dark bg?
![some](https://user-images.githubusercontent.com/35606353/93756854-62364480-fc23-11ea-8ad8-c3fb12d673f4.PNG)

is that what you want?

**Comment by UPstartDeveloper** [comment]
Oh sorry @rahulbhatt1899, I was actually referring to how a previous version of the templates in the `web/` would show a mostly black curve when I tried creating Chartist line graphs of the emissions data. The error is fixed now though, turns out I just forgot to load the Chartist CDN for the CSS styles.

Thanks for reaching out though, I appreciate your willingness to help! I will close this issue.
